# build image
FROM node:lts-alpine AS build
WORKDIR /source

RUN npm install -g vite

COPY ts/deucalion-ui/package*.json .
RUN npm ci

COPY ts/deucalion-ui/ .
RUN npm run build

# Package import-meta-env for runtime transforms.
#   https://iendeavor.github.io/import-meta-env/guide/getting-started/runtime-transform.html#without-node-js
RUN npx pkg ./node_modules/@import-meta-env/cli/bin/import-meta-env.js \
  --target node18-alpine-x64 \
  --output import-meta-env-alpine

# final image
FROM nginx:alpine
WORKDIR /usr/share/nginx/html

ENV DEUCALION_PAGE_TITLE="Deucalion Status" \
    DEUCALION_API_URL="" \
    DEUCALION_PROXY_API_URL="http://deucalion-api"

COPY --from=build /source/dist ./

# Copy nginx configuration templates
#   https://github.com/docker-library/docs/tree/master/nginx#using-environment-variables-in-nginx-configuration-new-in-119
COPY --from=build /source/nginx-templates/default.conf.template /etc/nginx/templates/

# Copy import-meta-env files
COPY --from=build /source/import-meta-env-alpine /source/.env /app/
COPY --from=build /source/docker-entrypoint.d/90-call-import-meta-env.sh /docker-entrypoint.d/
RUN chmod +x /docker-entrypoint.d/90-call-import-meta-env.sh
